# Generated by Django 4.2.7 on 2023-11-21 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrimonio',
            name='nome',
        ),
    ]
